// src/components/Card.tsx
// packages/ui/src/components/Card.tsx

import { forwardRef, ReactNode, memo, useCallback } from 'react'
import { cn } from '../lib/utils'

interface CardProps {
  children: ReactNode
  className?: string
  padding?: 'none' | 'sm' | 'md' | 'lg'
  shadow?: 'none' | 'sm' | 'md' | 'lg'
  hover?: boolean
  onClick?: () => void
}

interface CardHeaderProps {
  children: ReactNode
  className?: string
}

interface CardContentProps {
  children: ReactNode
  className?: string
}

interface CardTitleProps {
  children: ReactNode
  className?: string
}

interface CardDescriptionProps {
  children: ReactNode
  className?: string
}

interface CardFooterProps {
  children: ReactNode
  className?: string
}

const paddingClasses = {
  none: '',
  sm: 'p-4',
  md: 'p-6',
  lg: 'p-8',
} as const

const shadowClasses = {
  none: '',
  sm: 'shadow-sm',
  md: 'shadow-md',
  lg: 'shadow-lg',
} as const

export const Card = memo(
  forwardRef<HTMLDivElement, CardProps>(
    ({ children, className, padding = 'none', shadow = 'sm', hover = false, onClick }, ref) => {
      const handleClick = useCallback(() => onClick?.(), [onClick])

      return (
        <div
          ref={ref}
          className={cn(
            'rounded-lg border border-border bg-card text-foreground',
            // keep shadow controlled by prop
            shadowClasses[shadow],
            // hover behavior only when requested or clickable
            (hover || !!onClick) ? 'transition-shadow hover:shadow-md cursor-pointer' : '',
            paddingClasses[padding],
            className
          )}
          onClick={onClick ? handleClick : undefined}
        >
          {children}
        </div>
      )
    }
  )
)
Card.displayName = 'Card'

export const CardHeader = memo(
  forwardRef<HTMLDivElement, CardHeaderProps>(({ children, className }, ref) => (
    <div ref={ref} className={cn('flex flex-col space-y-1.5 p-6', className)}>
      {children}
    </div>
  ))
)
CardHeader.displayName = 'CardHeader'

export const CardTitle = memo(
  forwardRef<HTMLHeadingElement, CardTitleProps>(({ children, className }, ref) => (
    <h3 ref={ref} className={cn('text-2xl font-semibold leading-none tracking-tight', className)}>
      {children}
    </h3>
  ))
)
CardTitle.displayName = 'CardTitle'

export const CardDescription = memo(
  forwardRef<HTMLParagraphElement, CardDescriptionProps>(({ children, className }, ref) => (
    <p ref={ref} className={cn('text-sm text-muted-foreground', className)}>
      {children}
    </p>
  ))
)
CardDescription.displayName = 'CardDescription'

export const CardContent = memo(
  forwardRef<HTMLDivElement, CardContentProps>(({ children, className }, ref) => (
    <div ref={ref} className={cn('p-6 pt-0', className)}>
      {children}
    </div>
  ))
)
CardContent.displayName = 'CardContent'

export const CardFooter = memo(
  forwardRef<HTMLDivElement, CardFooterProps>(({ children, className }, ref) => (
    <div ref={ref} className={cn('flex items-center p-6 pt-0', className)}>
      {children}
    </div>
  ))
)
CardFooter.displayName = 'CardFooter'

// src/solid/components/Card.tsx
// packages/ui/src/solid/components/Card.tsx

import { Component, JSX, splitProps } from 'solid-js'
import { cn } from '../lib/utils'

interface CardProps {
  children: JSX.Element
  class?: string
  padding?: 'none' | 'sm' | 'md' | 'lg'
  shadow?: 'none' | 'sm' | 'md' | 'lg'
  hover?: boolean
  onClick?: () => void
  ref?: HTMLDivElement | ((el: HTMLDivElement) => void)
}

interface CardHeaderProps {
  children: JSX.Element
  class?: string
  ref?: HTMLDivElement | ((el: HTMLDivElement) => void)
}

interface CardContentProps {
  children: JSX.Element
  class?: string
  ref?: HTMLDivElement | ((el: HTMLDivElement) => void)
}

interface CardTitleProps {
  children: JSX.Element
  class?: string
  ref?: HTMLHeadingElement | ((el: HTMLHeadingElement) => void)
}

interface CardDescriptionProps {
  children: JSX.Element
  class?: string
  ref?: HTMLParagraphElement | ((el: HTMLParagraphElement) => void)
}

interface CardFooterProps {
  children: JSX.Element
  class?: string
  ref?: HTMLDivElement | ((el: HTMLDivElement) => void)
}

const paddingClasses = {
  none: '',
  sm: 'p-4',
  md: 'p-6',
  lg: 'p-8',
} as const

const shadowClasses = {
  none: '',
  sm: 'shadow-sm',
  md: 'shadow-md',
  lg: 'shadow-lg',
} as const

export const Card: Component<CardProps> = (props) => {
  const [local, others] = splitProps(props, ['children', 'class', 'padding', 'shadow', 'hover', 'onClick', 'ref'])

  const handleClick = () => local.onClick?.()

  return (
    <div
      ref={local.ref}
      class={cn(
        'rounded-lg border border-border bg-card text-foreground',
        shadowClasses[local.shadow ?? 'sm'],
        (local.hover || !!local.onClick) ? 'transition-shadow hover:shadow-md cursor-pointer' : '',
        paddingClasses[local.padding ?? 'none'],
        local.class
      )}
      onClick={local.onClick ? handleClick : undefined}
      {...others}
    >
      {local.children}
    </div>
  )
}

export const CardHeader: Component<CardHeaderProps> = (props) => {
  const [local, others] = splitProps(props, ['children', 'class', 'ref'])
  
  return (
    <div ref={local.ref} class={cn('flex flex-col space-y-1.5 p-6', local.class)} {...others}>
      {local.children}
    </div>
  )
}

export const CardTitle: Component<CardTitleProps> = (props) => {
  const [local, others] = splitProps(props, ['children', 'class', 'ref'])
  
  return (
    <h3 ref={local.ref} class={cn('text-2xl font-semibold leading-none tracking-tight', local.class)} {...others}>
      {local.children}
    </h3>
  )
}

export const CardDescription: Component<CardDescriptionProps> = (props) => {
  const [local, others] = splitProps(props, ['children', 'class', 'ref'])
  
  return (
    <p ref={local.ref} class={cn('text-sm text-muted-foreground', local.class)} {...others}>
      {local.children}
    </p>
  )
}

export const CardContent: Component<CardContentProps> = (props) => {
  const [local, others] = splitProps(props, ['children', 'class', 'ref'])
  
  return (
    <div ref={local.ref} class={cn('p-6 pt-0', local.class)} {...others}>
      {local.children}
    </div>
  )
}

export const CardFooter: Component<CardFooterProps> = (props) => {
  const [local, others] = splitProps(props, ['children', 'class', 'ref'])
  
  return (
    <div ref={local.ref} class={cn('flex items-center p-6 pt-0', local.class)} {...others}>
      {local.children}
    </div>
  )
}
