// src/react/components/Checkbox.tsx
// packages/ui/src/react/components/Checkbox.tsx

import { forwardRef, useId, useCallback, memo } from 'react'
import type { InputHTMLAttributes, ElementRef } from 'react'
import { cn } from '../lib/utils'
import { Check } from 'lucide-react'
import type { FormComponentProps } from '../lib/types'

interface CheckboxProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'onChange' | 'type'>, FormComponentProps {
  label?: string
  indeterminate?: boolean
  onChange?: (checked: boolean) => void
}

export const Checkbox = memo(forwardRef<ElementRef<'input'>, CheckboxProps>(
  ({ 
    label,
    error,
    helpText,
    indeterminate = false,
    checked = false,
    disabled = false,
    onChange,
    className,
    id,
    ...props 
  }, ref) => {
    const generatedId = useId()
    const checkboxId = id || generatedId
    const hasError = Boolean(error)

    const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
      onChange?.(e.target.checked)
    }, [onChange])

    const handleBoxClick = useCallback(() => {
      if (!disabled) {
        onChange?.(!checked)
      }
    }, [disabled, checked, onChange])

    const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
      if ((e.key === 'Enter' || e.key === ' ') && !disabled) {
        e.preventDefault()
        onChange?.(!checked)
      }
    }, [disabled, checked, onChange])

    return (
      <div className={cn('flex items-start', className)}>
        <div className='flex items-center h-5'>
          <div className='relative'>
            <input
              ref={ref}
              id={checkboxId}
              type='checkbox'
              checked={checked}
              disabled={disabled}
              onChange={handleChange}
              className='sr-only'
              aria-invalid={hasError}
              aria-describedby={
                error ? `${checkboxId}-error` : 
                helpText ? `${checkboxId}-help` : undefined
              }
              {...props}
            />
            <div
              className={cn(
                'w-4 h-4 border rounded transition-colors cursor-pointer flex items-center justify-center',
                checked || indeterminate
                  ? 'bg-blue-600 border-blue-600'
                  : 'bg-card border-border hover:border-muted-foreground',
                hasError 
                  ? 'border-red-300 focus-within:ring-red-500' 
                  : 'focus-within:ring-2 focus-within:ring-blue-500 focus-within:ring-offset-2',
                disabled && 'opacity-50 cursor-not-allowed'
              )}
              onClick={handleBoxClick}
              role='checkbox'
              aria-checked={indeterminate ? 'mixed' : checked}
              tabIndex={disabled ? -1 : 0}
              onKeyDown={handleKeyDown}
            >
              {checked && !indeterminate && (
                <Check className='w-3 h-3 text-white' strokeWidth={3} />
              )}
              {indeterminate && (
                <div className='w-2 h-0.5 bg-card rounded' />
              )}
            </div>
          </div>
        </div>
        
        {(label || helpText || error) && (
          <div className='ml-2 text-sm'>
            {label && (
              <label
                htmlFor={checkboxId}
                className={cn(
                  'block font-medium cursor-pointer',
                  hasError ? 'text-red-900' : 'text-foreground',
                  disabled && 'cursor-not-allowed opacity-50'
                )}
              >
                {label}
              </label>
            )}
            
            {error && (
              <p id={`${checkboxId}-error`} className='mt-1 text-red-600'>
                {error}
              </p>
            )}
            
            {helpText && !error && (
              <p id={`${checkboxId}-help`} className='mt-1 text-muted-foreground'>
                {helpText}
              </p>
            )}
          </div>
        )}
      </div>
    )
  }
))
Checkbox.displayName = 'Checkbox'

// src/solid/components/Checkbox.tsx
// packages/ui/src/solid/components/Checkbox.tsx

import { Component, JSX, splitProps, createUniqueId, Show } from 'solid-js'
import { cn } from '../lib/utils'
import { Check } from 'lucide-solid'
import type { FormComponentProps } from '../lib/types'

interface CheckboxProps extends Omit<JSX.InputHTMLAttributes<HTMLInputElement>, 'onChange' | 'type'>, FormComponentProps {
  label?: string
  indeterminate?: boolean
  checked?: boolean
  onChange?: (checked: boolean) => void
  ref?: HTMLInputElement | ((el: HTMLInputElement) => void)
}

export const Checkbox: Component<CheckboxProps> = (props) => {
  const [local, others] = splitProps(props, [
    'label',
    'error',
    'helpText',
    'indeterminate',
    'checked',
    'disabled',
    'onChange',
    'class',
    'id',
    'ref'
  ])

  const generatedId = createUniqueId()
  const checkboxId = () => local.id || generatedId
  const hasError = () => Boolean(local.error)
  const checked = () => local.checked ?? false
  const disabled = () => local.disabled ?? false
  const indeterminate = () => local.indeterminate ?? false

  const handleChange = (e: Event) => {
    const target = e.target as HTMLInputElement
    local.onChange?.(target.checked)
  }

  const handleBoxClick = () => {
    if (!disabled()) {
      local.onChange?.(!checked())
    }
  }

  const handleKeyDown = (e: KeyboardEvent) => {
    if ((e.key === 'Enter' || e.key === ' ') && !disabled()) {
      e.preventDefault()
      local.onChange?.(!checked())
    }
  }

  return (
    <div class={cn('flex items-start', local.class)}>
      <div class="flex items-center h-5">
        <div class="relative">
          <input
            ref={local.ref}
            id={checkboxId()}
            type="checkbox"
            checked={checked()}
            disabled={disabled()}
            onChange={handleChange}
            class="sr-only"
            aria-invalid={hasError()}
            aria-describedby={
              local.error ? `${checkboxId()}-error` : 
              local.helpText ? `${checkboxId()}-help` : undefined
            }
            {...others}
          />
          <div
            class={cn(
              'w-4 h-4 border rounded transition-colors cursor-pointer flex items-center justify-center',
              checked() || indeterminate()
                ? 'bg-blue-600 border-blue-600'
                : 'bg-card border-border hover:border-muted-foreground',
              hasError() 
                ? 'border-red-300 focus-within:ring-red-500' 
                : 'focus-within:ring-2 focus-within:ring-blue-500 focus-within:ring-offset-2',
              disabled() && 'opacity-50 cursor-not-allowed'
            )}
            onClick={handleBoxClick}
            role="checkbox"
            aria-checked={indeterminate() ? 'mixed' : checked()}
            tabIndex={disabled() ? -1 : 0}
            onKeyDown={handleKeyDown}
          >
            <Show when={checked() && !indeterminate()}>
              <Check class="w-3 h-3 text-white" stroke-width={3} />
            </Show>
            <Show when={indeterminate()}>
              <div class="w-2 h-0.5 bg-card rounded" />
            </Show>
          </div>
        </div>
      </div>
      
      <Show when={local.label || local.helpText || local.error}>
        <div class="ml-2 text-sm">
          <Show when={local.label}>
            <label
              for={checkboxId()}
              class={cn(
                'block font-medium cursor-pointer',
                hasError() ? 'text-red-900' : 'text-foreground',
                disabled() && 'cursor-not-allowed opacity-50'
              )}
            >
              {local.label}
            </label>
          </Show>
          
          <Show when={local.error}>
            <p id={`${checkboxId()}-error`} class="mt-1 text-red-600">
              {local.error}
            </p>
          </Show>
          
          <Show when={local.helpText && !local.error}>
            <p id={`${checkboxId()}-help`} class="mt-1 text-muted-foreground">
              {local.helpText}
            </p>
          </Show>
        </div>
      </Show>
    </div>
  )
}
