// src/react/components/Section.tsx
// packages/ui/src/react/components/Section.tsx

import { forwardRef, ReactNode, memo } from 'react';
import { cn } from '../lib/utils';

// Root Section component
interface SectionProps {
  children: ReactNode;
  className?: string;
  spacing?: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  id?: string;
}

const spacingClasses = {
  none: '',
  sm: 'mb-4',
  md: 'mb-6',
  lg: 'mb-8',
  xl: 'mb-12'
};

export const Section = memo(forwardRef<HTMLElement, SectionProps>(
  ({ children, className, spacing = 'none', id }, ref) => {
    return (
      <section
        ref={ref}
        id={id}
        className={cn(
          'w-full',
          spacingClasses[spacing],
          className
        )}
      >
        {children}
      </section>
    );
  }
));
Section.displayName = 'Section';

// SectionHeader component
interface SectionHeaderProps {
  children: ReactNode;
  className?: string;
  spacing?: 'none' | 'sm' | 'md' | 'lg';
}

const headerSpacingClasses = {
  none: '',
  sm: 'mb-2',
  md: 'mb-4',
  lg: 'mb-6'
};

export const SectionHeader = memo(forwardRef<HTMLDivElement, SectionHeaderProps>(
  ({ children, className, spacing = 'md' }, ref) => {
    return (
      <div
        ref={ref}
        className={cn(
          'flex flex-col',
          headerSpacingClasses[spacing],
          className
        )}
      >
        {children}
      </div>
    );
  }
));
SectionHeader.displayName = 'SectionHeader';

// SectionTitle component
interface SectionTitleProps {
  children: ReactNode;
  className?: string;
  size?: 'sm' | 'md' | 'lg' | 'xl';
  as?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
}

const titleSizeClasses = {
  sm: 'text-lg font-semibold',
  md: 'text-xl font-semibold',
  lg: 'text-2xl font-bold',
  xl: 'text-3xl font-bold'
};

export const SectionTitle = memo(forwardRef<HTMLHeadingElement, SectionTitleProps>(
  ({ children, className, size = 'md', as: Component = 'h2' }, ref) => {
    return (
      <Component
        ref={ref}
        className={cn(
          'text-foreground',
          titleSizeClasses[size],
          className
        )}
      >
        {children}
      </Component>
    );
  }
));
SectionTitle.displayName = 'SectionTitle';

// SectionDescription component
interface SectionDescriptionProps {
  children: ReactNode;
  className?: string;
  size?: 'sm' | 'md' | 'lg';
}

const descriptionSizeClasses = {
  sm: 'text-xs',
  md: 'text-sm',
  lg: 'text-base'
};

export const SectionDescription = memo(forwardRef<HTMLParagraphElement, SectionDescriptionProps>(
  ({ children, className, size = 'md' }, ref) => {
    return (
      <p
        ref={ref}
        className={cn(
          'text-muted-foreground mt-2',
          descriptionSizeClasses[size],
          className
        )}
      >
        {children}
      </p>
    );
  }
));
SectionDescription.displayName = 'SectionDescription';

// SectionContent component
interface SectionContentProps {
  children: ReactNode;
  className?: string;
}

export const SectionContent = memo(forwardRef<HTMLDivElement, SectionContentProps>(
  ({ children, className }, ref) => {
    return (
      <div
        ref={ref}
        className={cn('w-full', className)}
      >
        {children}
      </div>
    );
  }
));
SectionContent.displayName = 'SectionContent';

// CompoundSection - convenience component with header and content
interface CompoundSectionProps {
  children: ReactNode;
  title?: string;
  description?: string;
  titleSize?: 'sm' | 'md' | 'lg' | 'xl';
  spacing?: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  className?: string;
  id?: string;
}

export const CompoundSection = memo(forwardRef<HTMLElement, CompoundSectionProps>(
  ({
    children,
    title,
    description,
    titleSize = 'md',
    spacing = 'lg',
    className,
    id
  }, ref) => {
    return (
      <Section ref={ref} spacing={spacing} className={className} id={id}>
        {(title || description) && (
          <SectionHeader>
            {title && <SectionTitle size={titleSize}>{title}</SectionTitle>}
            {description && <SectionDescription>{description}</SectionDescription>}
          </SectionHeader>
        )}
        <SectionContent>{children}</SectionContent>
      </Section>
    );
  }
));
CompoundSection.displayName = 'CompoundSection';

// src/solid/components/Section.tsx
// packages/ui/src/solid/components/Section.tsx

import { type JSX, splitProps, mergeProps } from 'solid-js';
import { cn } from '../lib/utils';

// Root Section component
interface SectionProps {
  children: JSX.Element;
  class?: string;
  spacing?: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  id?: string;
  ref?: HTMLElement | ((el: HTMLElement) => void);
}

const spacingClasses = {
  none: '',
  sm: 'mb-4',
  md: 'mb-6',
  lg: 'mb-8',
  xl: 'mb-12'
};

export function Section(props: SectionProps) {
  const merged = mergeProps({ spacing: 'none' as const }, props);
  const [local, others] = splitProps(merged, ['children', 'class', 'spacing', 'ref']);

  return (
    <section
      ref={local.ref}
      class={cn(
        'w-full',
        spacingClasses[local.spacing],
        local.class
      )}
      {...others}
    >
      {local.children}
    </section>
  );
}

// SectionHeader component
interface SectionHeaderProps {
  children: JSX.Element;
  class?: string;
  spacing?: 'none' | 'sm' | 'md' | 'lg';
  ref?: HTMLDivElement | ((el: HTMLDivElement) => void);
}

const headerSpacingClasses = {
  none: '',
  sm: 'mb-2',
  md: 'mb-4',
  lg: 'mb-6'
};

export function SectionHeader(props: SectionHeaderProps) {
  const merged = mergeProps({ spacing: 'md' as const }, props);
  const [local, others] = splitProps(merged, ['children', 'class', 'spacing', 'ref']);

  return (
    <div
      ref={local.ref}
      class={cn(
        'flex flex-col',
        headerSpacingClasses[local.spacing],
        local.class
      )}
      {...others}
    >
      {local.children}
    </div>
  );
}

// SectionTitle component
interface SectionTitleProps {
  children: JSX.Element;
  class?: string;
  size?: 'sm' | 'md' | 'lg' | 'xl';
  as?: 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6';
  ref?: HTMLHeadingElement | ((el: HTMLHeadingElement) => void);
}

const titleSizeClasses = {
  sm: 'text-lg font-semibold',
  md: 'text-xl font-semibold',
  lg: 'text-2xl font-bold',
  xl: 'text-3xl font-bold'
};

export function SectionTitle(props: SectionTitleProps) {
  const merged = mergeProps({ size: 'md' as const, as: 'h2' as const }, props);
  const [local, others] = splitProps(merged, ['children', 'class', 'size', 'as', 'ref']);

  const Component = local.as;

  return (
    <Component
      ref={local.ref}
      class={cn(
        'text-foreground',
        titleSizeClasses[local.size],
        local.class
      )}
      {...others}
    >
      {local.children}
    </Component>
  );
}

// SectionDescription component
interface SectionDescriptionProps {
  children: JSX.Element;
  class?: string;
  size?: 'sm' | 'md' | 'lg';
  ref?: HTMLParagraphElement | ((el: HTMLParagraphElement) => void);
}

const descriptionSizeClasses = {
  sm: 'text-xs',
  md: 'text-sm',
  lg: 'text-base'
};

export function SectionDescription(props: SectionDescriptionProps) {
  const merged = mergeProps({ size: 'md' as const }, props);
  const [local, others] = splitProps(merged, ['children', 'class', 'size', 'ref']);

  return (
    <p
      ref={local.ref}
      class={cn(
        'text-muted-foreground mt-2',
        descriptionSizeClasses[local.size],
        local.class
      )}
      {...others}
    >
      {local.children}
    </p>
  );
}

// SectionContent component
interface SectionContentProps {
  children: JSX.Element;
  class?: string;
  ref?: HTMLDivElement | ((el: HTMLDivElement) => void);
}

export function SectionContent(props: SectionContentProps) {
  const [local, others] = splitProps(props, ['children', 'class', 'ref']);

  return (
    <div
      ref={local.ref}
      class={cn('w-full', local.class)}
      {...others}
    >
      {local.children}
    </div>
  );
}

// CompoundSection - convenience component with header and content
interface CompoundSectionProps {
  children: JSX.Element;
  title?: string;
  description?: string;
  titleSize?: 'sm' | 'md' | 'lg' | 'xl';
  spacing?: 'none' | 'sm' | 'md' | 'lg' | 'xl';
  class?: string;
  id?: string;
  ref?: HTMLElement | ((el: HTMLElement) => void);
}

export function CompoundSection(props: CompoundSectionProps) {
  const merged = mergeProps({ titleSize: 'md' as const, spacing: 'lg' as const }, props);
  const [local, others] = splitProps(merged, [
    'children',
    'title',
    'description',
    'titleSize',
    'spacing',
    'class',
    'ref'
  ]);

  return (
    <Section ref={local.ref} spacing={local.spacing} class={local.class} {...others}>
      {(local.title || local.description) && (
        <SectionHeader>
          {local.title && <SectionTitle size={local.titleSize}>{local.title}</SectionTitle>}
          {local.description && <SectionDescription>{local.description}</SectionDescription>}
        </SectionHeader>
      )}
      <SectionContent>{local.children}</SectionContent>
    </Section>
  );
}
